/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ejercicio_4;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.event.ActionListener;
import java.beans.EventHandler;

/**
 *
 * @author gag
 */
public class DialogSurvey4 extends javax.swing.JDialog {

    /**
     * Creates new form DialogSurvey
     */
    public DialogSurvey4(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        FlatDarkLaf.setup();
        initComponents();
        //comboListSport.setVisible(false);
        panelSports.remove(comboListSport);
        txtProfession.requestFocus();
        
        btnCancel.addActionListener(EventHandler.create(ActionListener.class, this, "dispose"));
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelContainer = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtProfession = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboAge = new javax.swing.JComboBox<>();
        spnFamily = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        panelSports = new javax.swing.JPanel();
        chkBoxSport = new javax.swing.JCheckBox();
        comboListSport = new javax.swing.JScrollPane();
        listSports = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jSlider2 = new javax.swing.JSlider();
        jSlider3 = new javax.swing.JSlider();
        jPanel7 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Personal Survey");
        setMinimumSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        panelContainer.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        panelContainer.setLayout(new javax.swing.BoxLayout(panelContainer, javax.swing.BoxLayout.Y_AXIS));

        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {80, 100, 20, 50, 100};
        jPanel1Layout.rowHeights = new int[] {30, 30};
        jPanel1Layout.columnWeights = new double[] {0.8, 1.0, 0.2, 0.5, 1.0};
        jPanel1.setLayout(jPanel1Layout);

        jLabel1.setText("Profesión");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(txtProfession, gridBagConstraints);

        jLabel2.setLabelFor(spnFamily);
        jLabel2.setText("Nº Hermanos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setLabelFor(comboAge);
        jLabel3.setText("Edad");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel3, gridBagConstraints);

        comboAge.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Menor de 18", "Entre 18 y 30 años", "Entre 30 y 65 años", "Mayor de 65" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(comboAge, gridBagConstraints);

        spnFamily.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(spnFamily, gridBagConstraints);

        panelContainer.add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Sexo"));
        jPanel2.setLayout(new java.awt.GridLayout(1, 3));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Hombre");
        jRadioButton2.setMargin(new java.awt.Insets(20, 20, 20, 20));
        jPanel2.add(jRadioButton2);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Mujer");
        jRadioButton3.setMargin(new java.awt.Insets(20, 20, 20, 20));
        jPanel2.add(jRadioButton3);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Otro");
        jRadioButton1.setMargin(new java.awt.Insets(20, 20, 20, 20));
        jPanel2.add(jRadioButton1);

        panelContainer.add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Deportes"));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        panelSports.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        panelSports.setLayout(new java.awt.BorderLayout());

        chkBoxSport.setText("¿Practica algún deporte?");
        chkBoxSport.setMargin(new java.awt.Insets(2, 2, 10, 2));
        chkBoxSport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBoxSportActionPerformed(evt);
            }
        });
        panelSports.add(chkBoxSport, java.awt.BorderLayout.PAGE_START);

        listSports.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Fútbol", "Tenis", "Tenis de Mesa", "Baloncesto", "Patinaje", "Surf" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listSports.setVisibleRowCount(5);
        comboListSport.setViewportView(listSports);

        panelSports.add(comboListSport, java.awt.BorderLayout.PAGE_END);

        jPanel3.add(panelSports);

        panelContainer.add(jPanel3);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Aficiones"));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        java.awt.GridBagLayout jPanel6Layout = new java.awt.GridBagLayout();
        jPanel6Layout.columnWeights = new double[] {0.3, 0.7};
        jPanel6Layout.rowWeights = new double[] {0.1, 0.3, 0.3, 0.3};
        jPanel6.setLayout(jPanel6Layout);

        jLabel4.setText("Marque del 1 al 10 en función de su grado de afición");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        jPanel6.add(jLabel4, gridBagConstraints);

        jLabel5.setText("Compras");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        jPanel6.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Televisión");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        jPanel6.add(jLabel6, gridBagConstraints);

        jLabel7.setText("Cine");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        jPanel6.add(jLabel7, gridBagConstraints);

        jSlider1.setMajorTickSpacing(1);
        jSlider1.setMaximum(10);
        jSlider1.setMinimum(1);
        jSlider1.setMinorTickSpacing(1);
        jSlider1.setPaintLabels(true);
        jSlider1.setSnapToTicks(true);
        jSlider1.setValue(5);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel6.add(jSlider1, gridBagConstraints);

        jSlider2.setMajorTickSpacing(1);
        jSlider2.setMaximum(10);
        jSlider2.setMinimum(1);
        jSlider2.setMinorTickSpacing(1);
        jSlider2.setPaintLabels(true);
        jSlider2.setSnapToTicks(true);
        jSlider2.setValue(5);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel6.add(jSlider2, gridBagConstraints);

        jSlider3.setMajorTickSpacing(1);
        jSlider3.setMaximum(10);
        jSlider3.setMinimum(1);
        jSlider3.setMinorTickSpacing(1);
        jSlider3.setPaintLabels(true);
        jSlider3.setSnapToTicks(true);
        jSlider3.setValue(5);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel6.add(jSlider3, gridBagConstraints);

        jPanel5.add(jPanel6);

        panelContainer.add(jPanel5);

        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 0, 0));
        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 0));

        jButton1.setText("Guardar");
        jPanel7.add(jButton1);

        btnCancel.setText("Cancelar");
        jPanel7.add(btnCancel);

        panelContainer.add(jPanel7);

        getContentPane().add(panelContainer);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkBoxSportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBoxSportActionPerformed
        if (chkBoxSport.isSelected()) {
            panelSports.add(comboListSport);
        } else {
            listSports.clearSelection();
            panelSports.remove(comboListSport);
        }
        panelSports.revalidate();
    }//GEN-LAST:event_chkBoxSportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogSurvey4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogSurvey4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogSurvey4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogSurvey4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogSurvey4 dialog = new DialogSurvey4(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkBoxSport;
    private javax.swing.JComboBox<String> comboAge;
    private javax.swing.JScrollPane comboListSport;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JSlider jSlider3;
    private javax.swing.JList<String> listSports;
    private javax.swing.JPanel panelContainer;
    private javax.swing.JPanel panelSports;
    private javax.swing.JSpinner spnFamily;
    private javax.swing.JTextField txtProfession;
    // End of variables declaration//GEN-END:variables
}
