/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejercicio_5;

import ejercicio_4.DialogSurvey4;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.beans.EventHandler;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.event.MouseInputAdapter;
import javax.swing.event.MouseInputListener;

/**
 *
 * @author gag
 */
public class EjemploInteractivo extends javax.swing.JFrame {

    /**
     * Creates new form EjemploInteractivo
     */
    public EjemploInteractivo() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        btnListener.addMouseListener(new EjemploMouseInputListener());
        btnAdapter.addMouseListener(new EjemploMouseInputAdapter());
        btnInner.addMouseListener(new EjemploInnerMouseInputAdapter());
        btnInnerAnonym.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                JDialog dialog = new DialogSurvey4((JFrame) SwingUtilities.getWindowAncestor(e.getComponent()), true);
                dialog.setVisible(true);
            }
        });
        btnEventHandler.addActionListener(EventHandler.create(ActionListener.class, this, "dispose"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnListener = new javax.swing.JButton();
        btnAdapter = new javax.swing.JButton();
        btnInner = new javax.swing.JButton();
        btnInnerAnonym = new javax.swing.JButton();
        btnEventHandler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnListener.setText("Mouse Input Listener");

        btnAdapter.setText("Mouse Input Adapter");

        btnInner.setText("Inner Class");

        btnInnerAnonym.setText("Inner Anonymous");

        btnEventHandler.setText("Event Handler");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnEventHandler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnInnerAnonym, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnListener, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnAdapter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInner, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(252, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnListener)
                .addGap(18, 18, 18)
                .addComponent(btnAdapter)
                .addGap(18, 18, 18)
                .addComponent(btnInner)
                .addGap(18, 18, 18)
                .addComponent(btnInnerAnonym)
                .addGap(18, 18, 18)
                .addComponent(btnEventHandler)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EjemploInteractivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EjemploInteractivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EjemploInteractivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EjemploInteractivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EjemploInteractivo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdapter;
    private javax.swing.JButton btnEventHandler;
    private javax.swing.JButton btnInner;
    private javax.swing.JButton btnInnerAnonym;
    private javax.swing.JButton btnListener;
    // End of variables declaration//GEN-END:variables

    private static class EjemploInnerMouseInputAdapter extends MouseAdapter{
        @Override
        public void mouseClicked(MouseEvent e) {
            JDialog dialog = new DialogSurvey4((JFrame) SwingUtilities.getWindowAncestor(e.getComponent()), true);
            dialog.setVisible(true);
        }
    }
}
